.translation: &translation-base
    image: crowdin/cli
    script:
        - echo crowdin upload sources
        - crowdin upload sources --token $CROWDIN_API_TOKEN --project-id $CROWDIN_PROJECT_ID
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

stages:
    - translation
    - version
    - build
    - update

translation:
    stage: translation
    <<: *translation-base
